const sharedProductionEnv = {
  NODE_ENV: "production",
  PORT: process.env.PORT || 5002,
  DATABASE_URL: process.env.DATABASE_URL,
  SECRET: process.env.SECRET,
  CLIENT_URL: process.env.CLIENT_URL,
  FRONTEND_URL: process.env.FRONTEND_URL,
  EXTRA_ORIGINS: process.env.EXTRA_ORIGINS || "",
  HTTPS_ONLY: process.env.HTTPS_ONLY || "false",
  ENABLE_HTTPS_HEADERS: process.env.ENABLE_HTTPS_HEADERS || "false",
  TLS_KEY_FILE: process.env.TLS_KEY_FILE || "",
  TLS_CERT_FILE: process.env.TLS_CERT_FILE || "",
  HTTPS_PORT: process.env.HTTPS_PORT || process.env.PORT || 5002,
  HTTP_REDIRECT_PORT: process.env.HTTP_REDIRECT_PORT || "",
  TRUST_PROXY: process.env.TRUST_PROXY || "1",
  UPLOAD_DIR: process.env.UPLOAD_DIR || "uploads",
  UPLOAD_BACKUP_DIR: process.env.UPLOAD_BACKUP_DIR || "backups/uploads",
  UPLOAD_ALLOWED_MIME: process.env.UPLOAD_ALLOWED_MIME || "image/jpeg,image/png,image/webp",
  UPLOAD_MAX_BYTES: process.env.UPLOAD_MAX_BYTES || "5242880",
  UPLOAD_MAX_WIDTH: process.env.UPLOAD_MAX_WIDTH || "1920",
  UPLOAD_MAX_HEIGHT: process.env.UPLOAD_MAX_HEIGHT || "1920",
  UPLOAD_QUALITY: process.env.UPLOAD_QUALITY || "82",
  UPLOAD_TARGET_FORMAT: process.env.UPLOAD_TARGET_FORMAT || "webp",
  UPLOAD_ORPHAN_RETENTION_HOURS: process.env.UPLOAD_ORPHAN_RETENTION_HOURS || "24",
  UPLOAD_BACKUP_RETENTION_DAYS: process.env.UPLOAD_BACKUP_RETENTION_DAYS || "14",
  UPLOAD_BACKUP_CRON: process.env.UPLOAD_BACKUP_CRON || "20 3 * * *",
  UPLOAD_CLEANUP_CRON: process.env.UPLOAD_CLEANUP_CRON || "50 3 * * *",
  DB_BACKUP_CRON: process.env.DB_BACKUP_CRON || "0 3 * * *",
  MAIL_USER: process.env.MAIL_USER,
  MAIL_PASS: process.env.MAIL_PASS,
  GOOGLE_PROJECT_ID: process.env.GOOGLE_PROJECT_ID,
  GOOGLE_CLIENT_EMAIL: process.env.GOOGLE_CLIENT_EMAIL,
  GOOGLE_CALENDAR_ID: process.env.GOOGLE_CALENDAR_ID,
  GOOGLE_PRIVATE_KEY: process.env.GOOGLE_PRIVATE_KEY,
};

module.exports = {
  apps: [
    {
      name: "tracking-system-backend",
      script: "./server.js",
      log_date_format: "YYYY-MM-DD HH:mm Z",
      error_file: "./logs/error.log",
      out_file: "./logs/out.log",
      merge_logs: true,
      max_memory_restart: "500M",
      env_production: sharedProductionEnv,
    },
    {
      name: "db-backup-cron",
      script: "./scripts/backup_db.js",
      instances: 1,
      exec_mode: "fork",
      cron_restart: "0 2 * * *",
      autorestart: false,
      watch: false,
      env_production: sharedProductionEnv,
    },
  ],
};
