import React, { useEffect, useState } from 'react';
import useAuthStore from '../../../store/auth-store';
import { getAnnualStats } from '../../../api/report';
import { AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts';
import * as XLSX from 'xlsx';
import { Download } from 'lucide-react';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import ExportButtons from '../../../components/admin/ExportButtons';
import dayjs from 'dayjs';

const AnnualReport = () => {
    const { token } = useAuthStore();
    const [data, setData] = useState([]);
    const [loading, setLoading] = useState(true);
    const [year, setYear] = useState(dayjs().year());

    useEffect(() => {
        loadData();
    }, [year]);

    const loadData = async () => {
        try {
            setLoading(true);
            const res = await getAnnualStats(token, year);
            setData(res.data);
        } catch (err) {
            console.error(err);
        } finally {
            setLoading(false);
        }
    };

    const exportPDF = () => {
        const doc = new jsPDF();

        // Header
        doc.setFontSize(20);
        doc.text(`Annual Report: ${year}`, 14, 20);
        doc.setFontSize(10);
        doc.text(`Generated: ${new Date().toLocaleDateString()}`, 14, 28);

        // Data Table
        const tableColumn = ["Month", "Total Tickets", "Fixed", "Pending"];
        const tableRows = data.map(item => [
            item.name,
            item.total,
            item.fixed,
            item.total - item.fixed // inferred pending
        ]);

        autoTable(doc, {
            startY: 35,
            head: [tableColumn],
            body: tableRows,
            theme: 'grid',
            headStyles: { fillColor: [59, 130, 246] }, // Blue header
            styles: { fontSize: 10 },
        });

        // Footer
        const pageCount = doc.internal.getNumberOfPages();
        for (let i = 1; i <= pageCount; i++) {
            doc.setPage(i);
            doc.setFontSize(10);
            doc.text('Generated by Admin System', 14, doc.internal.pageSize.height - 10);
            doc.text(`Page ${i} of ${pageCount}`, doc.internal.pageSize.width - 30, doc.internal.pageSize.height - 10);
        }

        doc.save(`annual_report_${year}.pdf`);
    };

    const exportExcel = () => {
        const ws = XLSX.utils.json_to_sheet(data);
        const wb = XLSX.utils.book_new();
        XLSX.utils.book_append_sheet(wb, ws, "Annual Data");
        XLSX.writeFile(wb, `annual_report_${year}.xlsx`);
    };

    return (
        <div className="space-y-6">
            <div className="flex items-center justify-between bg-white p-4 rounded-2xl shadow-sm border border-gray-100">
                <div className="flex items-center gap-2 bg-gray-50 px-3 py-2 rounded-xl border border-gray-100">
                    <select value={year} onChange={e => setYear(e.target.value)} className="bg-transparent border-none text-sm font-semibold text-gray-700 focus:ring-0 cursor-pointer">
                        {[2024, 2025, 2026].map(y => (
                            <option key={y} value={y}>{y}</option>
                        ))}
                    </select>
                </div>
            </div>

            {loading ? <p>Loading...</p> : (
                <>
                    <div id="annual-report-content" className="bg-white p-6 border rounded-2xl h-96 shadow-sm">
                        <h3 className="font-bold mb-6 text-xl text-gray-800">Annual Trend</h3>
                        <ResponsiveContainer width="100%" height="90%">
                            <AreaChart data={data}>
                                <CartesianGrid strokeDasharray="3 3" vertical={false} />
                                <XAxis dataKey="name" axisLine={false} tickLine={false} dy={10} />
                                <YAxis axisLine={false} tickLine={false} />
                                <Tooltip contentStyle={{ borderRadius: '12px', border: 'none', boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1)' }} />
                                <Area type="monotone" dataKey="total" stroke="#3B82F6" fill="url(#colorTotal)" name="Total Tickets" strokeWidth={3} />
                                <Area type="monotone" dataKey="fixed" stroke="#10B981" fill="url(#colorFixed)" name="Fixed" strokeWidth={3} />
                                <defs>
                                    <linearGradient id="colorTotal" x1="0" y1="0" x2="0" y2="1">
                                        <stop offset="5%" stopColor="#3B82F6" stopOpacity={0.1} />
                                        <stop offset="95%" stopColor="#3B82F6" stopOpacity={0} />
                                    </linearGradient>
                                    <linearGradient id="colorFixed" x1="0" y1="0" x2="0" y2="1">
                                        <stop offset="5%" stopColor="#10B981" stopOpacity={0.1} />
                                        <stop offset="95%" stopColor="#10B981" stopOpacity={0} />
                                    </linearGradient>
                                </defs>
                            </AreaChart>
                        </ResponsiveContainer>
                    </div>

                    <ExportButtons onExportPDF={exportPDF} onExportExcel={exportExcel} />
                </>
            )}
        </div>
    );
};

export default AnnualReport;
