import React, { useEffect, useState } from 'react';
import useAuthStore from '../../../store/auth-store';
import { getEquipmentStats } from '../../../api/report';
import { PieChart, Pie, Cell, Tooltip, Legend, ResponsiveContainer, BarChart, Bar, XAxis, YAxis, CartesianGrid } from 'recharts';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import * as XLSX from 'xlsx';
import ExportButtons from '../../../components/admin/ExportButtons';

const EquipmentAnalysis = () => {
    const { token } = useAuthStore();
    const [data, setData] = useState([]);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        loadData();
    }, []);

    const loadData = async () => {
        try {
            setLoading(true);
            const res = await getEquipmentStats(token);
            // res.data is array of { amount, name, room }
            setData(res.data);
        } catch (err) {
            console.error(err);
        } finally {
            setLoading(false);
        }
    };

    const COLORS = ['#0088FE', '#00C49F', '#FFBB28', '#FF8042', '#8884d8', '#82ca9d'];

    const exportPDF = () => {
        const doc = new jsPDF();

        // Header
        doc.setFontSize(20);
        doc.text('Equipment Analysis Report', 14, 20);
        doc.setFontSize(10);
        doc.text(`Generated: ${new Date().toLocaleDateString()}`, 14, 28);

        // Data Table
        const tableColumn = ["Rank", "Equipment Name", "Room", "Issue Count"];
        const tableRows = data.map((item, index) => [
            index + 1,
            item.name,
            item.room,
            item.amount
        ]);

        autoTable(doc, {
            startY: 35,
            head: [tableColumn],
            body: tableRows,
            theme: 'grid',
            headStyles: { fillColor: [59, 130, 246] }, // Blue header
            styles: { fontSize: 10 },
        });

        // Footer
        const pageCount = doc.internal.getNumberOfPages();
        for (let i = 1; i <= pageCount; i++) {
            doc.setPage(i);
            doc.setFontSize(10);
            doc.text('Generated by Admin System', 14, doc.internal.pageSize.height - 10);
            doc.text(`Page ${i} of ${pageCount}`, doc.internal.pageSize.width - 30, doc.internal.pageSize.height - 10);
        }

        doc.save(`equipment_analysis_${new Date().toISOString().split('T')[0]}.pdf`);
    };

    const exportExcel = () => {
        const ws = XLSX.utils.json_to_sheet(data);
        const wb = XLSX.utils.book_new();
        XLSX.utils.book_append_sheet(wb, ws, "Equipment Data");
        XLSX.writeFile(wb, `equipment_analysis_${new Date().toISOString().split('T')[0]}.xlsx`);
    };

    return (
        <div className="space-y-6">
            <h2 className="text-lg font-bold">Top Problematic Equipment</h2>

            {loading ? <p>Loading...</p> : (
                <>
                    <div id="equipment-analysis-content" className="grid md:grid-cols-2 gap-6 bg-white p-6 rounded-2xl">
                        {/* Chart */}
                        <div className="bg-white p-4 border rounded-lg h-80">
                            <ResponsiveContainer width="100%" height="100%">
                                <PieChart>
                                    <Pie
                                        data={data}
                                        cx="50%"
                                        cy="50%"
                                        labelLine={false}
                                        label={({ name, percent }) => `${name} ${(percent * 100).toFixed(0)}%`}
                                        outerRadius={80}
                                        fill="#8884d8"
                                        dataKey="amount"
                                    >
                                        {data.map((entry, index) => (
                                            <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
                                        ))}
                                    </Pie>
                                    <Tooltip />
                                    <Legend />
                                </PieChart>
                            </ResponsiveContainer>
                        </div>

                        {/* Table */}
                        <div className="bg-white border rounded-lg overflow-hidden">
                            <table className="w-full text-sm text-left">
                                <thead className="bg-gray-50 text-gray-700 font-bold">
                                    <tr>
                                        <th className="p-3">Rank</th>
                                        <th className="p-3">Equipment</th>
                                        <th className="p-3">Room</th>
                                        <th className="p-3 text-right">Issues</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {data.map((item, index) => (
                                        <tr key={index} className="border-t hover:bg-gray-50">
                                            <td className="p-3 font-bold text-gray-500">#{index + 1}</td>
                                            <td className="p-3 font-medium">{item.name}</td>
                                            <td className="p-3 text-gray-500">{item.room}</td>
                                            <td className="p-3 text-right font-bold text-red-500">{item.amount}</td>
                                        </tr>
                                    ))}
                                </tbody>
                            </table>
                        </div>
                    </div>

                    <ExportButtons onExportPDF={exportPDF} onExportExcel={exportExcel} />
                </>
            )}
        </div>
    );
};

export default EquipmentAnalysis;
