import React, { useEffect, useState } from 'react';
import useAuthStore from '../../../store/auth-store';
import { getSatisfactionStats } from '../../../api/report';
import { ResponsiveContainer, BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, Cell } from 'recharts';
import { Star, MessageSquare, AlertCircle } from 'lucide-react';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import * as XLSX from 'xlsx';
import ExportButtons from '../../../components/admin/ExportButtons';

const SatisfactionReport = () => {
    const { token } = useAuthStore();
    const [data, setData] = useState(null);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState(null);

    useEffect(() => {
        loadData();
    }, []);

    const loadData = async () => {
        try {
            setLoading(true);
            const res = await getSatisfactionStats(token);
            setData(res.data);
            setError(null);
        } catch (err) {
            console.error("Failed to load satisfaction stats", err);
            setError("Failed to load data. Please try again.");
        } finally {
            setLoading(false);
        }
    };

    const COLORS = ['#EF4444', '#F97316', '#EAB308', '#22C55E', '#16A34A']; // 1 to 5 stars

    if (loading) return (
        <div className="flex justify-center items-center h-64">
            <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600"></div>
        </div>
    );

    if (error) return (
        <div className="flex flex-col items-center justify-center h-64 text-red-500">
            <AlertCircle size={48} className="mb-2" />
            <p>{error}</p>
        </div>
    );

    if (!data || data.totalRated === 0) return (
        <div className="flex flex-col items-center justify-center h-96 bg-gray-50 rounded-xl border-2 border-dashed border-gray-200 text-gray-400">
            <Star size={48} className="mb-4 text-gray-300" />
            <p className="text-lg font-medium">No feedback received yet</p>
            <p className="text-sm">User ratings and comments will appear here.</p>
        </div>
    );

    // Prepare chart data: ensure keys 1-5 exist
    const chartData = [1, 2, 3, 4, 5].map(star => ({
        name: `${star} Stars`,
        value: data.distribution[star] || 0
    }));

    const exportPDF = () => {
        const doc = new jsPDF();

        // Header
        doc.setFontSize(20);
        doc.text('Satisfaction Report', 14, 20);
        doc.setFontSize(10);
        doc.text(`Generated: ${new Date().toLocaleDateString()}`, 14, 28);

        // Summary Statistics Section
        doc.setFontSize(14);
        doc.text('Summary Statistics', 14, 38);

        const summaryColumn = ["Metric", "Value"];
        const summaryRows = [
            ["Total Rated", data.totalRated],
            ["Average Rating", `${data.averageRating.toFixed(2)} / 5.0`]
        ];
        // Add star distribution data
        Object.entries(data.distribution).forEach(([star, count]) => {
            summaryRows.push([`${star} Stars`, count]);
        });

        autoTable(doc, {
            startY: 42,
            head: [summaryColumn],
            body: summaryRows,
            theme: 'grid',
            headStyles: { fillColor: [59, 130, 246] },
            styles: { fontSize: 10 },
            margin: { left: 14, right: 100 } // Keep summary table narrower
        });

        // Recent Feedback Section
        const finalY = doc.lastAutoTable.finalY || 50;
        doc.text('Recent Feedback Details', 14, finalY + 15);

        const feedbackColumn = ["Date", "Rating", "User Comment", "Assigned IT"];
        const feedbackRows = data.recentFeedback.map(item => [
            new Date(item.createdAt).toLocaleDateString(),
            `${item.rating} Stars`,
            item.userFeedback || "No comment",
            item.assignedTo?.name || "Unknown"
        ]);

        autoTable(doc, {
            startY: finalY + 20,
            head: [feedbackColumn],
            body: feedbackRows,
            theme: 'grid',
            headStyles: { fillColor: [59, 130, 246] },
            styles: { fontSize: 10 },
            columnStyles: { 2: { cellWidth: 80 } } // Wider column for comments
        });

        // Footer
        const pageCount = doc.internal.getNumberOfPages();
        for (let i = 1; i <= pageCount; i++) {
            doc.setPage(i);
            doc.setFontSize(10);
            doc.text('Generated by Admin System', 14, doc.internal.pageSize.height - 10);
            doc.text(`Page ${i} of ${pageCount}`, doc.internal.pageSize.width - 30, doc.internal.pageSize.height - 10);
        }

        doc.save(`satisfaction_report_${new Date().toISOString().split('T')[0]}.pdf`);
    };

    const exportExcel = () => {
        // Feedback Sheet
        const feedbackWs = XLSX.utils.json_to_sheet(data.recentFeedback.map(item => ({
            Date: new Date(item.createdAt).toLocaleDateString(),
            Rating: item.rating,
            Comment: item.userFeedback,
            AssignedTo: item.assignedTo?.name
        })));

        // Summary Sheet
        const summaryData = [
            { Metric: "Average Rating", Value: data.averageRating.toFixed(2) },
            { Metric: "Total Rated", Value: data.totalRated },
            ...Object.entries(data.distribution).map(([stars, count]) => ({ Metric: `${stars} Stars`, Value: count }))
        ];
        const summaryWs = XLSX.utils.json_to_sheet(summaryData);

        const wb = XLSX.utils.book_new();
        XLSX.utils.book_append_sheet(wb, summaryWs, "Summary");
        XLSX.utils.book_append_sheet(wb, feedbackWs, "Feedback");
        XLSX.writeFile(wb, `satisfaction_report_${new Date().toISOString().split('T')[0]}.xlsx`);
    };

    return (
        <div className="space-y-6 animate-fade-in">
            <div id="satisfaction-report-content" className="space-y-6 p-4 bg-white rounded-2xl">
                {/* Summary Cards */}
                <div className="grid grid-cols-2 gap-4">
                    <div className="bg-blue-50 p-6 rounded-lg text-center border border-blue-100">
                        <h3 className="text-blue-600 font-bold text-lg mb-2">Total Rated</h3>
                        <p className="text-4xl font-bold text-gray-800">{data.totalRated}</p>
                    </div>
                    <div className="bg-yellow-50 p-6 rounded-lg text-center border border-yellow-100">
                        <h3 className="text-yellow-600 font-bold text-lg mb-2">Average Rating</h3>
                        <div className="flex items-center justify-center gap-2">
                            <span className="text-4xl font-bold text-gray-800">{data.averageRating.toFixed(1)}</span>
                            <Star size={32} className="text-yellow-500 fill-yellow-500" />
                        </div>
                    </div>
                </div>

                <div className="grid md:grid-cols-2 gap-6">
                    {/* Chart */}
                    <div className="bg-white p-4 border rounded-lg h-96 shadow-sm">
                        <h3 className="font-bold mb-4 text-gray-700">Rating Distribution</h3>
                        <div className="h-80 w-full">
                            <ResponsiveContainer width="100%" height="100%">
                                <BarChart data={chartData} margin={{ top: 20, right: 30, left: 0, bottom: 5 }}>
                                    <CartesianGrid strokeDasharray="3 3" vertical={false} />
                                    <XAxis dataKey="name" axisLine={false} tickLine={false} />
                                    <YAxis allowDecimals={false} axisLine={false} tickLine={false} />
                                    <Tooltip
                                        cursor={{ fill: '#f3f4f6' }}
                                        contentStyle={{ borderRadius: '8px', border: 'none', boxShadow: '0 4px 6px -1px rgb(0 0 0 / 0.1)' }}
                                    />
                                    <Bar dataKey="value" radius={[4, 4, 0, 0]}>
                                        {chartData.map((entry, index) => (
                                            <Cell key={`cell-${index}`} fill={COLORS[index]} />
                                        ))}
                                    </Bar>
                                </BarChart>
                            </ResponsiveContainer>
                        </div>
                    </div>

                    {/* Recent Comments */}
                    <div className="bg-white border rounded-lg p-4 h-96 shadow-sm flex flex-col">
                        <h3 className="font-bold mb-4 flex items-center gap-2 text-gray-700">
                            <MessageSquare size={18} /> Recent Feedback
                        </h3>
                        <div className="flex-1 overflow-y-auto pr-2 space-y-4 custom-scrollbar">
                            {data.recentFeedback.length === 0 ? (
                                <p className="text-center text-gray-400 py-8">No comments yet</p>
                            ) : (
                                data.recentFeedback.map((item, index) => (
                                    <div key={index} className="border-b border-gray-100 pb-3 last:border-0 hover:bg-gray-50 p-2 rounded transition-colors">
                                        <div className="flex justify-between items-start mb-1">
                                            <div className="flex gap-1">
                                                {[...Array(5)].map((_, i) => (
                                                    <Star
                                                        key={i}
                                                        size={12}
                                                        className={i < item.rating ? "fill-yellow-400 text-yellow-400" : "text-gray-200"}
                                                    />
                                                ))}
                                            </div>
                                            <span className="text-xs text-gray-400">
                                                {new Date(item.createdAt).toLocaleDateString()}
                                            </span>
                                        </div>
                                        <p className="text-sm text-gray-600 italic">"{item.userFeedback || "No comment"}"</p>
                                        <div className="flex items-center gap-1 mt-2">
                                            <span className="text-xs text-gray-400">Support by:</span>
                                            <span className="text-xs font-medium text-gray-600 bg-gray-100 px-2 py-0.5 rounded-full">
                                                {item.assignedTo?.name || "Unknown"}
                                            </span>
                                        </div>
                                    </div>
                                ))
                            )}
                        </div>
                    </div>
                </div>
            </div>

            <ExportButtons onExportPDF={exportPDF} onExportExcel={exportExcel} />
        </div>
    );
};

export default SatisfactionReport;
