-- AlterTable
ALTER TABLE `Product` ADD COLUMN `amount` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `netWeight` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `weightIn` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `weightOut` DOUBLE NOT NULL DEFAULT 0;
